CREATE DATABASE IF NOT EXISTS mydb DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE mydb;

CREATE TABLE IF NOT EXISTS t1 (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  info VARCHAR(100) NOT NULL,
  create_time DATETIME(3) NOT NULL,
  update_time DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS t2 (
  id BIGINT UNSIGNED NOT NULL,
  create_time DATETIME(3) NOT NULL,
  info VARCHAR(100) NOT NULL,
  status TINYINT NOT NULL DEFAULT 0,
  KEY idx_id (id),
  KEY idx_create_time (create_time)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
